### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/infografia-salathiel1999#2]
[Barrera Valencia Irvin s.pdf](https://github.com/SistemasTecTlaxiaco/infografia-salathiel1999/files/7157883/Barrera.Valencia.Irvin.s.pdf)

**Comment by Sandra631** [comment]
Reviso Sandra Yolotzin Reyes García
90 puntos-----18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
